//! Wind charge visual effects: projectile rendering, trail coloring, and
//! burst particle generation on impact.

/// Maximum lifetime of a wind charge projectile in seconds.
const MAX_LIFETIME: f32 = 3.0;

/// Default speed of a wind charge projectile (blocks per second).
const DEFAULT_SPEED: f32 = 1.5;

/// Default collision radius of a wind charge projectile.
const DEFAULT_RADIUS: f32 = 0.3;

/// Number of particles generated by a wind burst on impact.
const BURST_PARTICLE_COUNT: usize = 20;

/// A wind charge projectile with position, velocity, size, and age tracking.
#[derive(Debug, Clone, Copy)]
pub struct WindChargeVisual {
    /// World-space position of the wind charge.
    pub pos: [f32; 3],
    /// Current velocity in blocks per second.
    pub velocity: [f32; 3],
    /// Collision/visual radius of the projectile.
    pub radius: f32,
    /// Seconds since the wind charge was spawned.
    pub age: f32,
}

/// Spawn a new wind charge from `origin` traveling in `direction`.
///
/// The direction is normalized internally; passing a zero vector produces a
/// stationary charge. Speed is 1.5 blocks/s, radius is 0.3.
pub fn spawn_wind_charge(origin: [f32; 3], direction: [f32; 3]) -> WindChargeVisual {
    let len = (direction[0] * direction[0]
        + direction[1] * direction[1]
        + direction[2] * direction[2])
    .sqrt();

    let velocity = if len > 1e-6 {
        [
            direction[0] / len * DEFAULT_SPEED,
            direction[1] / len * DEFAULT_SPEED,
            direction[2] / len * DEFAULT_SPEED,
        ]
    } else {
        [0.0, 0.0, 0.0]
    };

    WindChargeVisual {
        pos: origin,
        velocity,
        radius: DEFAULT_RADIUS,
        age: 0.0,
    }
}

/// Advance a wind charge by `dt` seconds, updating position and age.
///
/// Returns `true` if the charge is still alive (age < 3 seconds), `false` if
/// it has expired and should be removed.
pub fn tick_wind_charge(wc: &mut WindChargeVisual, dt: f32) -> bool {
    wc.age += dt;

    wc.pos[0] += wc.velocity[0] * dt;
    wc.pos[1] += wc.velocity[1] * dt;
    wc.pos[2] += wc.velocity[2] * dt;

    wc.age < MAX_LIFETIME
}

/// Generate burst particles at `impact_pos` for the wind charge explosion.
///
/// Returns 20 `(position, velocity)` pairs representing white swirling
/// particles emanating from the impact point. `seed` ensures deterministic
/// output for identical calls.
pub fn wind_burst_particles(
    impact_pos: [f32; 3],
    radius: f32,
    seed: u64,
) -> Vec<([f32; 3], [f32; 3])> {
    let mut particles = Vec::with_capacity(BURST_PARTICLE_COUNT);

    for i in 0..BURST_PARTICLE_COUNT {
        let h = hash_u64(seed, i as u32);

        // Map hash bits to direction components in [-1, 1].
        let x = ((h & 0xFFFF) as f32 / 32767.5) - 1.0;
        let y = (((h >> 16) & 0xFFFF) as f32 / 32767.5) - 1.0;
        let z = (((h >> 32) & 0xFFFF) as f32 / 32767.5) - 1.0;

        let len = (x * x + y * y + z * z).sqrt().max(1e-6);
        let nx = x / len;
        let ny = y / len;
        let nz = z / len;

        // Speed varies per particle based on remaining hash bits.
        let speed = radius * (0.8 + ((h >> 48) & 0xFF) as f32 / 637.5);

        let pos = [
            impact_pos[0] + nx * radius * 0.1,
            impact_pos[1] + ny * radius * 0.1,
            impact_pos[2] + nz * radius * 0.1,
        ];

        let vel = [nx * speed, ny * speed, nz * speed];

        particles.push((pos, vel));
    }

    particles
}

/// Return the RGBA trail color for wind charge particles.
///
/// A translucent light blue-white: `[0.8, 0.9, 1.0, 0.4]`.
pub fn wind_trail_color() -> [f32; 4] {
    [0.8, 0.9, 1.0, 0.4]
}

/// Deterministic 64-bit hash from a seed and particle index.
fn hash_u64(seed: u64, index: u32) -> u64 {
    let mut h = seed
        .wrapping_mul(6_364_136_223_846_793_005)
        .wrapping_add(index as u64)
        .wrapping_mul(1_442_695_040_888_963_407);
    h ^= h >> 33;
    h = h.wrapping_mul(0xff51afd7ed558ccd);
    h ^= h >> 33;
    h = h.wrapping_mul(0xc4ceb9fe1a85ec53);
    h ^= h >> 33;
    h
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- spawn_wind_charge ---

    #[test]
    fn spawn_starts_at_origin() {
        let origin = [10.0, 20.0, 30.0];
        let wc = spawn_wind_charge(origin, [1.0, 0.0, 0.0]);
        assert_eq!(wc.pos, origin);
    }

    #[test]
    fn spawn_has_zero_age() {
        let wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]);
        assert!(wc.age.abs() < f32::EPSILON);
    }

    #[test]
    fn spawn_has_default_radius() {
        let wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]);
        assert!((wc.radius - 0.3).abs() < 1e-6);
    }

    #[test]
    fn spawn_normalizes_direction_to_speed_1_5() {
        let wc = spawn_wind_charge([0.0, 0.0, 0.0], [3.0, 0.0, 0.0]);
        let speed = (wc.velocity[0] * wc.velocity[0]
            + wc.velocity[1] * wc.velocity[1]
            + wc.velocity[2] * wc.velocity[2])
        .sqrt();
        assert!(
            (speed - 1.5).abs() < 1e-5,
            "speed should be 1.5, got {speed}"
        );
    }

    #[test]
    fn spawn_diagonal_direction_has_correct_speed() {
        let wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 1.0, 1.0]);
        let speed = (wc.velocity[0] * wc.velocity[0]
            + wc.velocity[1] * wc.velocity[1]
            + wc.velocity[2] * wc.velocity[2])
        .sqrt();
        assert!(
            (speed - 1.5).abs() < 1e-5,
            "diagonal speed should be 1.5, got {speed}"
        );
    }

    #[test]
    fn spawn_zero_direction_produces_stationary_charge() {
        let wc = spawn_wind_charge([0.0, 0.0, 0.0], [0.0, 0.0, 0.0]);
        assert_eq!(wc.velocity, [0.0, 0.0, 0.0]);
    }

    // --- tick_wind_charge ---

    #[test]
    fn tick_advances_age() {
        let mut wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]);
        tick_wind_charge(&mut wc, 0.5);
        assert!((wc.age - 0.5).abs() < 1e-5);
    }

    #[test]
    fn tick_moves_position() {
        let mut wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]);
        tick_wind_charge(&mut wc, 1.0);
        assert!(
            (wc.pos[0] - 1.5).abs() < 1e-5,
            "x should be 1.5, got {}",
            wc.pos[0]
        );
        assert!(wc.pos[1].abs() < 1e-5);
        assert!(wc.pos[2].abs() < 1e-5);
    }

    #[test]
    fn tick_returns_true_while_alive() {
        let mut wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]);
        assert!(tick_wind_charge(&mut wc, 1.0));
        assert!(tick_wind_charge(&mut wc, 1.0));
    }

    #[test]
    fn tick_returns_false_when_expired() {
        let mut wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]);
        assert!(tick_wind_charge(&mut wc, 2.9));
        assert!(!tick_wind_charge(&mut wc, 0.2));
    }

    #[test]
    fn tick_expires_exactly_at_3_seconds() {
        let mut wc = spawn_wind_charge([0.0, 0.0, 0.0], [1.0, 0.0, 0.0]);
        // Advance to exactly 3.0 seconds
        assert!(!tick_wind_charge(&mut wc, 3.0));
    }

    #[test]
    fn multiple_ticks_accumulate() {
        let mut wc = spawn_wind_charge([0.0, 0.0, 0.0], [0.0, 0.0, 1.0]);
        tick_wind_charge(&mut wc, 0.5);
        tick_wind_charge(&mut wc, 0.5);
        assert!((wc.age - 1.0).abs() < 1e-5);
        assert!(
            (wc.pos[2] - 1.5).abs() < 1e-5,
            "z should be 1.5, got {}",
            wc.pos[2]
        );
    }

    // --- wind_burst_particles ---

    #[test]
    fn burst_returns_20_particles() {
        let particles = wind_burst_particles([0.0, 0.0, 0.0], 1.0, 42);
        assert_eq!(particles.len(), 20);
    }

    #[test]
    fn burst_particles_near_impact() {
        let impact = [10.0, 20.0, 30.0];
        let particles = wind_burst_particles(impact, 1.0, 99);
        for (pos, _vel) in &particles {
            let dx = pos[0] - impact[0];
            let dy = pos[1] - impact[1];
            let dz = pos[2] - impact[2];
            let dist = (dx * dx + dy * dy + dz * dz).sqrt();
            assert!(
                dist < 1.0,
                "particle should start near impact, dist={dist}"
            );
        }
    }

    #[test]
    fn burst_particles_have_nonzero_velocity() {
        let particles = wind_burst_particles([0.0, 0.0, 0.0], 1.0, 7);
        for (_pos, vel) in &particles {
            let speed_sq = vel[0] * vel[0] + vel[1] * vel[1] + vel[2] * vel[2];
            assert!(speed_sq > 0.01, "velocity should be nonzero");
        }
    }

    #[test]
    fn burst_is_deterministic() {
        let a = wind_burst_particles([5.0, 5.0, 5.0], 2.0, 123);
        let b = wind_burst_particles([5.0, 5.0, 5.0], 2.0, 123);
        for ((pa, va), (pb, vb)) in a.iter().zip(b.iter()) {
            assert_eq!(pa, pb);
            assert_eq!(va, vb);
        }
    }

    #[test]
    fn burst_different_seeds_differ() {
        let a = wind_burst_particles([0.0, 0.0, 0.0], 1.0, 1);
        let b = wind_burst_particles([0.0, 0.0, 0.0], 1.0, 2);
        let any_differ = a
            .iter()
            .zip(b.iter())
            .any(|((_, va), (_, vb))| va != vb);
        assert!(any_differ, "different seeds should produce different results");
    }

    #[test]
    fn burst_radius_scales_velocity() {
        let small = wind_burst_particles([0.0, 0.0, 0.0], 0.5, 42);
        let large = wind_burst_particles([0.0, 0.0, 0.0], 2.0, 42);

        let avg_speed = |particles: &[([f32; 3], [f32; 3])]| -> f32 {
            let total: f32 = particles
                .iter()
                .map(|(_, v)| (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt())
                .sum();
            total / particles.len() as f32
        };

        assert!(
            avg_speed(&large) > avg_speed(&small),
            "larger radius should produce faster particles"
        );
    }

    // --- wind_trail_color ---

    #[test]
    fn trail_color_is_correct() {
        let c = wind_trail_color();
        assert!((c[0] - 0.8).abs() < 1e-6);
        assert!((c[1] - 0.9).abs() < 1e-6);
        assert!((c[2] - 1.0).abs() < 1e-6);
        assert!((c[3] - 0.4).abs() < 1e-6);
    }

    #[test]
    fn trail_color_is_translucent() {
        let c = wind_trail_color();
        assert!(c[3] > 0.0 && c[3] < 1.0, "trail should be translucent");
    }
}
